url: "https://quanta-science.github.io"
baseurl: ""
permalink: pretty
default_image: "/assets/img/preview.png"

collections:
  math:
    output: true
    permalink: /math/:path/
  phys:
    output: true
    permalink: /phys/:path/
  chem:
    output: true
    permalink: /chem/:path/
  misc:
    output: true
    permalink: /misc/:path/

plugins:
  - jekyll-sitemap