url: "https://quanta-science.github.io"
baseurl: ""
permalink: pretty
default_image: "/assets/img/preview.png"

collections:
  math:
    output: true
    permalink: /:path/
  phys:
    output: true
    permalink: /:path/
  chem:
    output: true
    permalink: /:path/
  misc:
    output: true
    permalink: /:path/

plugins:
  - jekyll-sitemap