url: "https://quanta-science.github.io"
baseurl: ""
permalink: pretty
default_image: "/assets/img/preview.png"

collections:
  math:
    output: true
    permalink: /math/:path/
    nav_order: 1
    meta_label: Математика
    nav: true
  phys:
    output: true
    permalink: /phys/:path/
    nav_order: 2
    meta_label: Физика
    nav: true
  chem:
    output: true
    permalink: /chem/:path/
    nav_order: 3
    meta_label: Химия
    nav: true
  misc:
    output: true
    permalink: /misc/:path/
    nav_order: 4
    meta_label: Разное
    nav: true
  navg:
    output: true
    permalink: /:path/
    nav_order: 5
    meta_label: Навигаторы
    nav: true

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-remote-theme
